name: Perform unit tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install PyPDF2
        pip install dateparser
        pip install alto-xml
        pip install nltk

    - name: Test with unittest
      env: # authentication
        KBLAB_USERNAME: ${{ secrets.KBLAB_USERNAME }}
        KBLAB_PASSWORD: ${{ secrets.KBLAB_PASSWORD }}
      run: |
        python -m unittest test.schemas
        python -m unittest test.mp
        python -m unittest test.altocheck

    - name: Test metadata integrity
      run: |
        echo "Test that there are no duplicates in the DB"
        echo "throw ERROR on inconsistencies on our side"
        echo "WARN on upstream errors"

        python -m unittest test.db
    - name: Test notebooks
      run: |
        pip install pytest nbmake
        pytest --nbmake **/*ipynb
